meta-otab-uki: final changes needed for update to work
Mostly changes to otab/otab-shell so they change BootOrder

or BootNext via efibootmgr

Signed-off-by: Michał Iwanicki <michal.iwanicki@3mdeb.com>

diff --git a/meta-zarhus-features/meta-otab/meta-otab-uki/dynamic-layers/zarhus-distro/recipes-zarhus/images/files/otab-shell b/meta-zarhus-features/meta-otab/meta-otab-uki/dynamic-layers/zarhus-distro/recipes-zarhus/images/files/otab-shell
--- a/meta-zarhus-features/meta-otab/meta-otab-uki/dynamic-layers/zarhus-distro/recipes-zarhus/images/files/otab-shell
+++ b/meta-zarhus-features/meta-otab/meta-otab-uki/dynamic-layers/zarhus-distro/recipes-zarhus/images/files/otab-shell
@@ -14,13 +14,31 @@ do_preinst()
 
 do_postinst()
 {
+    otab_label="$1"
     echo "do_postinst"
-    if [ -z "$OTAB_LABEL" ]; then
+    if [ -z "$otab_label" ]; then
         echo "OTAB_LABEL not given through the 'data' attribute in sw-description"
         exit 1
     fi
 
-    e2label "$UPDATE_DEV_SYMLINK" "$OTAB_LABEL"
+    case "$otab_label" in
+    "<OTAB_LABEL_ROOTFS_A>")
+        next_boot="ZarhusOS A"
+        ;;
+    "<OTAB_LABEL_ROOTFS_B>")
+        next_boot="ZarhusOS B"
+        ;;
+    *)
+        echo "Unknown Label: $otab_label"
+        exit 1
+        ;;
+    esac
+
+    boot_num=$(efibootmgr | grep -om1 "Boot.* ${next_boot}" | sed -r 's/Boot([0-9]+).*/\1/')
+    if ! efibootmgr --bootnext "$boot_num" >/dev/null; then
+        echo "Failed to set $next_boot as next boot"
+        exit 1
+    fi
 
     exit 0
 }
@@ -32,9 +50,8 @@ preinst)
     ;;
 postinst)
     # passed through the 'data = ' attribute in sw-description
-    OTAB_LABEL="$2"
     echo "call do_postinst"
-    do_postinst
+    do_postinst "$2"
     ;;
 *)
     echo "default"
